// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
/* eslint-disable unicorn/no-abusive-eslint-disable */
/* eslint-disable */
import * as fs from "node:fs";

import { defineBuildConfig } from "unbuild";

const packageJson = JSON.parse(fs.readFileSync("./package.json").toString());

export default defineBuildConfig({
  entries: ["src/index"],
  externals: [
    ...Object.keys(packageJson.dependencies ?? []),
    ...Object.keys(packageJson.devDependencies ?? []),
    ...Object.keys(packageJson.peerDependencies ?? []),
  ],
});
