export * from "./commands/index.js"
export {
  BatchExecuteStatementCommand,
  type BatchExecuteStatementCommandInput,
  type BatchExecuteStatementCommandOutput,
  BatchGetItemCommand,
  type BatchGetItemCommandInput,
  type BatchGetItemCommandOutput,
  BatchWriteItemCommand,
  type BatchWriteItemCommandInput,
  type BatchWriteItemCommandOutput,
  CreateBackupCommand,
  type CreateBackupCommandInput,
  type CreateBackupCommandOutput,
  CreateGlobalTableCommand,
  type CreateGlobalTableCommandInput,
  type CreateGlobalTableCommandOutput,
  CreateTableCommand,
  type CreateTableCommandInput,
  type CreateTableCommandOutput,
  DeleteBackupCommand,
  type DeleteBackupCommandInput,
  type DeleteBackupCommandOutput,
  DeleteItemCommand,
  type DeleteItemCommandInput,
  type DeleteItemCommandOutput,
  DeleteTableCommand,
  type DeleteTableCommandInput,
  type DeleteTableCommandOutput,
  DescribeBackupCommand,
  type DescribeBackupCommandInput,
  type DescribeBackupCommandOutput,
  DescribeContinuousBackupsCommand,
  type DescribeContinuousBackupsCommandInput,
  type DescribeContinuousBackupsCommandOutput,
  DescribeContributorInsightsCommand,
  type DescribeContributorInsightsCommandInput,
  type DescribeContributorInsightsCommandOutput,
  DescribeEndpointsCommand,
  type DescribeEndpointsCommandInput,
  type DescribeEndpointsCommandOutput,
  DescribeExportCommand,
  type DescribeExportCommandInput,
  type DescribeExportCommandOutput,
  DescribeGlobalTableCommand,
  type DescribeGlobalTableCommandInput,
  type DescribeGlobalTableCommandOutput,
  DescribeGlobalTableSettingsCommand,
  type DescribeGlobalTableSettingsCommandInput,
  type DescribeGlobalTableSettingsCommandOutput,
  DescribeKinesisStreamingDestinationCommand,
  type DescribeKinesisStreamingDestinationCommandInput,
  type DescribeKinesisStreamingDestinationCommandOutput,
  DescribeLimitsCommand,
  type DescribeLimitsCommandInput,
  type DescribeLimitsCommandOutput,
  DescribeTableCommand,
  type DescribeTableCommandInput,
  type DescribeTableCommandOutput,
  DescribeTableReplicaAutoScalingCommand,
  type DescribeTableReplicaAutoScalingCommandInput,
  type DescribeTableReplicaAutoScalingCommandOutput,
  DescribeTimeToLiveCommand,
  type DescribeTimeToLiveCommandInput,
  type DescribeTimeToLiveCommandOutput,
  DisableKinesisStreamingDestinationCommand,
  type DisableKinesisStreamingDestinationCommandInput,
  type DisableKinesisStreamingDestinationCommandOutput,
  EnableKinesisStreamingDestinationCommand,
  type EnableKinesisStreamingDestinationCommandInput,
  type EnableKinesisStreamingDestinationCommandOutput,
  ExecuteStatementCommand,
  type ExecuteStatementCommandInput,
  type ExecuteStatementCommandOutput,
  ExecuteTransactionCommand,
  type ExecuteTransactionCommandInput,
  type ExecuteTransactionCommandOutput,
  ExportTableToPointInTimeCommand,
  type ExportTableToPointInTimeCommandInput,
  type ExportTableToPointInTimeCommandOutput,
  GetItemCommand,
  type GetItemCommandInput,
  type GetItemCommandOutput,
  ListBackupsCommand,
  type ListBackupsCommandInput,
  type ListBackupsCommandOutput,
  ListContributorInsightsCommand,
  type ListContributorInsightsCommandInput,
  type ListContributorInsightsCommandOutput,
  ListExportsCommand,
  type ListExportsCommandInput,
  type ListExportsCommandOutput,
  ListGlobalTablesCommand,
  type ListGlobalTablesCommandInput,
  type ListGlobalTablesCommandOutput,
  ListTablesCommand,
  type ListTablesCommandInput,
  type ListTablesCommandOutput,
  ListTagsOfResourceCommand,
  type ListTagsOfResourceCommandInput,
  type ListTagsOfResourceCommandOutput,
  // PutItemCommand,
  // type PutItemCommandInput,
  // type PutItemCommandOutput,
  // QueryCommand,
  // type QueryCommandInput,
  // type QueryCommandOutput,
  RestoreTableFromBackupCommand,
  type RestoreTableFromBackupCommandInput,
  type RestoreTableFromBackupCommandOutput,
  RestoreTableToPointInTimeCommand,
  type RestoreTableToPointInTimeCommandInput,
  type RestoreTableToPointInTimeCommandOutput,
  ScanCommand,
  type ScanCommandInput,
  type ScanCommandOutput,
  TagResourceCommand,
  type TagResourceCommandInput,
  type TagResourceCommandOutput,
  TransactGetItemsCommand,
  type TransactGetItemsCommandInput,
  type TransactGetItemsCommandOutput,
  TransactWriteItemsCommand,
  type TransactWriteItemsCommandInput,
  type TransactWriteItemsCommandOutput,
  UntagResourceCommand,
  type UntagResourceCommandInput,
  type UntagResourceCommandOutput,
  UpdateContinuousBackupsCommand,
  type UpdateContinuousBackupsCommandInput,
  type UpdateContinuousBackupsCommandOutput,
  UpdateContributorInsightsCommand,
  type UpdateContributorInsightsCommandInput,
  type UpdateContributorInsightsCommandOutput,
  UpdateGlobalTableCommand,
  type UpdateGlobalTableCommandInput,
  type UpdateGlobalTableCommandOutput,
  UpdateGlobalTableSettingsCommand,
  type UpdateGlobalTableSettingsCommandInput,
  type UpdateGlobalTableSettingsCommandOutput,
  // UpdateItemCommand,
  // type UpdateItemCommandInput,
  // type UpdateItemCommandOutput,
  UpdateTableCommand,
  type UpdateTableCommandInput,
  type UpdateTableCommandOutput,
  UpdateTableReplicaAutoScalingCommand,
  type UpdateTableReplicaAutoScalingCommandInput,
  type UpdateTableReplicaAutoScalingCommandOutput,
  UpdateTimeToLiveCommand,
  type UpdateTimeToLiveCommandInput,
  type UpdateTimeToLiveCommandOutput,
} from "@aws-sdk/client-dynamodb"
export * from "./dynamodb-client.js"
